# Generated by Django 3.1.1 on 2020-09-22 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, choices=[('Customer', 'Customer'), ('Resturant Owner', 'Resturant Owner')], max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=50)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('avatar', models.ImageField(default='profiles/default.jpg', max_length=250, upload_to='profiles')),
                ('address', models.CharField(blank=True, max_length=100)),
                ('bio', models.CharField(blank=True, max_length=250)),
                ('blood_group', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
