# Generated by Django 3.1.1 on 2020-09-25 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('image', models.ImageField(default='food/default.jpg', max_length=250, upload_to='food')),
                ('description', models.CharField(blank=True, max_length=250)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('price', models.FloatField(blank=True, max_length=50)),
                ('discount', models.FloatField(blank=True, max_length=50)),
                ('quantity', models.IntegerField(blank=True, max_length=50)),
                ('food_available', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(blank=True, choices=[('Paid Review', 'Paid Review'), ('Advertise', 'Advertise'), ('Customer Review', 'Customer Review')], max_length=50)),
                ('item_name', models.CharField(blank=True, max_length=250)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('thumbnail', models.ImageField(default='postthumb/default.jpg', max_length=250, upload_to='postthumb')),
                ('address', models.CharField(blank=True, max_length=100)),
                ('price', models.FloatField(blank=True, max_length=50)),
                ('restaurant_name', models.CharField(blank=True, max_length=250)),
                ('rating', models.FloatField(blank=True, max_length=50)),
                ('views', models.IntegerField(default=0)),
                ('down_vote', models.ManyToManyField(blank=True, related_name='down_vote', to=settings.AUTH_USER_MODEL)),
                ('up_vote', models.ManyToManyField(blank=True, related_name='up_vote', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('booking_system', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('avatar', models.ImageField(default='restaurant/default.jpg', max_length=250, upload_to='restaurant')),
                ('address', models.CharField(blank=True, max_length=100)),
                ('about_us', models.CharField(blank=True, max_length=250)),
                ('discount', models.FloatField(blank=True, max_length=50)),
                ('time_schedule', models.CharField(blank=True, max_length=50)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResturantGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(upload_to='resturant')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Moderator', 'Moderator')], max_length=50)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(upload_to='post')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostComent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.post')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, max_length=50)),
                ('vat', models.FloatField(blank=True, max_length=50)),
                ('Delivery_charge', models.FloatField(blank=True, max_length=50)),
                ('total_price', models.FloatField(blank=True, max_length=50)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fooditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fooditem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.restaurant'),
        ),
    ]
