# Generated by Django 3.1.1 on 2020-09-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
